#! /bin/bash

# Run tests for formats of interest. Must list all formats of interest;
# there is no option to omit formats from --all.

# Search for format_list in gyptest.py to see the list of formats.
# Currently the list is make, msvs, ninja and xcode.

# Note that test/lib/TestGyp.py makes sure it uses the gyp command
# in this directory not the installed gyp so no need for something
# like export PYTHONPATH=.:$PYTHONPATH.

./gyptest.py -f msvs -a

